---
kind: common.Repository
spec:
  conformLicenseCheck: false
  license:
    enabled: false
---
kind: common.Image
name: image-drone-downstream
spec:
  pushLatest: false
  droneExtraEnvironment:
    PLATFORM: linux/amd64,linux/arm64
---
kind: golang.Build
spec:
  outputs:
    linux-amd64:
      GOOS: linux
      GOARCH: amd64
    linux-arm64:
      GOOS: linux
      GOARCH: arm64
