# commit to be tagged for the new release
commit = "HEAD"

project_name = "drone-downstream"
github_repo = "drone-plugins/drone-downstream"
match_deps = "^github.com/(drone-plugins/[a-zA-Z0-9-]+)$"

# previous = -
# pre_release = true

# [notes]
